#The goal of this yml is to have the parameters of the created data points
#params:
#number_of_individuals: int  The number of points created 
#number_dimension: int The dimension in which points are
#limit_min: int The minimum value a point can take on a dimension
#limit_max: int The maximum value a point can take on a dimension

number_of_individuals: 1000

number_dimension: 2

limit_min: -1000

limit_max: 1000